// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rfkjjlatobcdmhumgkkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJma2pqbGF0b2JjZG1odW1na2toIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NjU5ODIsImV4cCI6MjA2MjQ0MTk4Mn0.s8L2TjuVSFnIB6sKIe-NtixyO6e0JqE8qD9sekBLu08";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);